import { useState, useEffect } from "react";
import type { PolicyFormState, CompiledPolicy, PolicyConfig } from "../types/policy";

export function useCompiler(policyDoc: PolicyFormState) {
  const [compiled, setCompiled] = useState<CompiledPolicy | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    const compile = async () => {
      setLoading(true);
      setError(null);

      try {
        const config: PolicyConfig = {};
        const summaryParts: string[] = [];

        if (policyDoc.maxAmount.enabled) {
          const limitNum = parseFloat(policyDoc.maxAmount.limit);
          if (isNaN(limitNum) || limitNum <= 0) {
            throw new Error("Max amount must be a positive number");
          }

          const limitWei = BigInt(Math.floor(limitNum * 1e18)).toString();

          config.maxAmount = {
            enabled: true,
            limit: limitWei,
          };

          summaryParts.push(`Max ${limitNum} MCK per transaction`);
        }

        if (policyDoc.timeWindow?.enabled) {
          const { startHour, endHour } = policyDoc.timeWindow;

          if (startHour < 0 || startHour > 23 || endHour < 0 || endHour > 23) {
            throw new Error("Hours must be between 0 and 23");
          }

          config.timeWindow = {
            enabled: true,
            startHour,
            endHour,
          };

          if (startHour <= endHour) {
            summaryParts.push(`Active ${startHour}:00-${endHour}:00 UTC`);
          } else {
            summaryParts.push(`Active ${startHour}:00-${endHour}:00 UTC (overnight)`);
          }
        }

        if (policyDoc.whitelist?.enabled) {
          const addresses = policyDoc.whitelist.addresses;

          if (addresses.length === 0) {
            throw new Error("Whitelist enabled but no addresses provided");
          }

          if (addresses.length > 4) {
            throw new Error("Maximum 4 addresses supported (Merkle tree depth 2)");
          }

          // Store addresses - Merkle tree will be generated by backend
          config.whitelist = {
            enabled: true,
            addresses,
          };

          summaryParts.push(`${addresses.length} whitelisted recipient${addresses.length > 1 ? 's' : ''}`);
        }

        const summary = summaryParts.length > 0 
          ? summaryParts.join(" • ") 
          : "No policies configured";

        setCompiled({
          valid: true,
          config,
          summary,
        });
      } catch (err: any) {
        setError(err.message);
        setCompiled({
          valid: false,
          config: {},
          summary: "",
          errors: [err.message],
        });
      } finally {
        setLoading(false);
      }
    };

    compile();
  }, [policyDoc]);

  return { compiled, loading, error };
}
